version: '3.8'

volumes:
  sqlserver_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$Sa_Password:SecureDatabase@123
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
  
  productmanager.api:
    image: productmanager.api
    build:
      context: src
      dockerfile: ProductManager.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:8080
    command: >
      sh -c "dotnet ef database update &&
             dotnet ProductManager.API.dll"

